### ISSUE TITLE
prepping for merge upstream

### ISSUE THREAD

**Issue by zerog2k** [BotInABoxER/marlin2-for-wanhao-i3#3]
first of all, thanks for putting this together... I had started with that older version of marlin 1.1.3 from the thingiverse post, and quickly discovered your 1.1.9, then saw that you had ported to 2.0 - wonderful.
So I'm able to get mine working quite well. I have made a few minor mods via configuration.h (like manual bilinear ABL and corner leveling in menus, etc).

However, I'm seeing lots of activity on bugfix-2.0.x branch upstream, and I'm wondering how best to keep this updated. It may be possible to just pull and merge locally, but I'm wondering what unique changes here for Duplicator i3 w/ Melzi board can be PR'ed back up to Marlin repo, such that anything we add is basically through standard customization/configuration

Perhaps even coming up with another melzi board variant, etc. (Along with the custom thermistor tables, etc).

**Comment by mtpiercey** [comment]
Hmm... I like these ideas. Personally, I think a pull request to the Marlin repo proper to get an example configuration folder for the i3 would work best at this point. Further, I don't think it'd be difficult to basically make a list of the changes made to this version as opposed to the upstream that can be updated every time Marlin is (since it's just minor configuration tweaks here/there, really - plus the thermistor table which I basically generated using Marlin's table generator Python script).

**Comment by zerog2k** [comment]
Ok, let me know how i can help it along. I'm pretty good w/ github and arduino, but new to Marlin, hence just getting familiar with the structure. (Scored a "broken" Duplicator i3 for 10 bucks, which had the hotbed connector overheating issue, so I want to use Marlin on it... The original fw is ... painful ...)

**Comment by mtpiercey** [comment]
Very cool. I agree that the stock firmware was a mess. The only thing I miss from the original was the slick print time counter/length counter, though I don't know how accurate that was. I think that the best way forward at this point would simply be to make an example configuration for the Wanhao i3 then open a pull request to have it added. The "custom" thermistor table (or at least the instructions for generating it) could potentially go in a "README" inside the example configurations file. I'll make a fork of 2.0.x Marlin today, and see if I can get the ball rolling.

**Comment by zerog2k** [comment]
closing out, as I'm able to compile upstream marlin bugfix-2.0.x branch now, thanks so much for this mtpiercy!

**Comment by mtpiercey** [comment]
Glad to hear it!
